# Generated by Django 4.0.2 on 2022-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='location',
            field=models.CharField(default='Columbia, MD (HQ)', max_length=100),
            preserve_default=False,
        ),
    ]
