# Generated by Django 4.0.2 on 2022-02-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0003_bioinfo_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='client',
            field=models.CharField(choices=[('AARP', 'AARP'), ('Acorns', 'Acorns'), ('CVS', 'CVS'), ('Grammarly', 'Grammarly'), ('HGV', 'HGV'), ('Marriott MTA', 'Marriott MTA'), ('Sunovion', 'Sunovion'), ('Visa', 'Visa'), ('Walmart', 'Walmart')], default='CVS', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='industry',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Grocery', 'Grocery'), ('Financial Services', 'Financial Services'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('B2B', 'B2B'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance')], default='Insurance', max_length=300),
            preserve_default=False,
        ),
    ]
