# Generated by Django 4.0.3 on 2022-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0006_alter_bioinfo_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='bio_ppt',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='intro',
            field=models.TextField(default='This is a bio placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
