# Generated by Django 4.0.3 on 2022-03-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0007_bioinfo_bio_ppt_bioinfo_intro_bioinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
