# Generated by Django 4.0.3 on 2022-03-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0008_alter_bioinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='bio_ppt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='industry',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Grocery', 'Grocery'), ('Financial Services', 'Financial Services'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('B2B', 'B2B'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Communication Services', 'Communication Services'), ('E Commerce', 'E Commerce'), ('Educational Services', 'Educational Services'), ('Energy', 'Energy'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information Technology'), ('Life Sciences', 'Life Sciences'), ('Real Estate', 'Real Estate'), ('Technology', 'Technology')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='location',
            field=models.CharField(choices=[('Columbia, MD (HQ)', 'Columbia, MD (HQ)'), ('New York, NY', 'New York, NY'), ('Denver, CO', 'Denver, CO'), ('India', 'India'), ('Remote', 'Remote')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='position',
            field=models.CharField(choices=[('Associate Data Scientist/Intern', 'Associate Data Scientist/Intern'), ('Associate Data Scientist, All-Star', 'Associate Data Scientist, All-Star'), ('Lead Data Scientist', 'Lead Data Scientist'), ('Senior Manager, Data Science', 'Senior Manager, Data Science'), ('Director, Data Science', 'Director, Data Science'), ('Senior Data Scientist', 'Senior Data Scientist'), ('Data Scientist', 'Associate Director, Data Science'), ('Manager, Data Science', 'Manager, Data Science '), ('Senior Director, Data Science', 'Senior Director, Data Science'), ('Marketing Scientist, All-Star', 'Marketing Scientist, All-Star'), ('Senior Marketing Scientist', 'Senior Marketing Scientist'), ('Associate Marketing Scientist, All-Star', 'Associate Marketing Scientist, All-Star'), ('VP, Data Science', 'VP, Data Science'), ('SVP, Data Science', 'SVP, Data Science')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='skill',
            field=models.CharField(choices=[('Predictive Modeling', 'Predictive Modeling'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Natural Language Processing', 'Natural Language Processing'), ('Recommendation System', 'Recommendation System'), ('LTV', 'LTV'), ('Optimization', 'Optimization'), ('Markov Chain', 'Markov Chain'), ('Measurement', 'Measurement'), ('AB Testing', 'AB Testing'), ('Business Intelligence', 'Business Intelligence'), ('Campaign Design / Execution', 'Campaign Design / Execution'), ('Cloud Services', 'Cloud Services'), ('Customer Segmentation and Insights', 'Customer Segmentation and Insights'), ('Data Governence', 'Data Governence'), ('Data Visualization', 'Data Visualization'), ('Data Wrangling', 'Data Wrangling'), ('Data / Network Security', 'Data / Network Security'), ('Deployment', 'Deployment'), ('Digital Analytics', 'Digital Analytics'), ('Personalization', 'Personalization'), ('SEO', 'SEO'), ('Simulation', 'Simulation'), ('Time Series Analysis', 'Time Series Analysis')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='bioinfo',
            name='technique',
            field=models.CharField(choices=[('Python', 'Python'), ('SQL', 'SQL'), ('Spark', 'Spark'), ('GCP', 'GCP'), ('AWS', 'AWS'), ('Databricks', 'Databricks'), ('R', 'R'), ('Snowflakes', 'Snowflakes'), ('Java', 'Java'), ('C/C++', 'C/C++')], default=None, max_length=300),
        ),
    ]
