# Generated by Django 4.0.3 on 2022-03-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0009_student_alter_bioinfo_bio_ppt_alter_bioinfo_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
