# Generated by Django 4.0.3 on 2022-03-10 06:42

import bios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0013_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio_ppt',
            field=models.FileField(blank=True, null=True, upload_to=bios.models.path_and_rename2),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bios.models.path_and_rename),
        ),
    ]
