# Generated by Django 4.0.2 on 2022-03-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0014_alter_student_bio_ppt_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='text',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
