# Generated by Django 4.0.2 on 2022-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0015_bioinfo_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='business_domain',
            field=models.CharField(blank=True, choices=[('Sales & Marketing', 'Sales & Marketing'), ('Supply Chain', 'Supply Chain'), ('Pricing', 'Pricing'), ('Product', 'Product'), ('Finance', 'Finance'), ('IoT', 'IoT'), ('HR', 'HR'), ('Real Estate', 'Real Estate'), ('Manufacturing', 'Manufacturing'), ('Customer Experience', 'Customer Experience')], max_length=300, null=True),
        ),
    ]
