# Generated by Django 4.0.2 on 2022-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0016_remove_bioinfo_text_bioinfo_business_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='major',
            field=models.CharField(default='Data Science', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='university',
            field=models.CharField(default='University of Maryland', max_length=300),
            preserve_default=False,
        ),
    ]
