# Generated by Django 4.0.2 on 2022-04-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0017_bioinfo_major_bioinfo_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
