# Generated by Django 4.0.2 on 2022-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0018_bioinfo_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio_ppt',
            field=models.FileField(blank=True, null=True, upload_to='bio_ppt/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
