# Generated by Django 4.0.2 on 2022-04-14 17:46

import bios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0019_alter_student_bio_ppt_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio_ppt',
            field=models.FileField(blank=True, null=True, upload_to=bios.models.path_and_rename2),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bios.models.path_and_rename),
        ),
    ]
