# Generated by Django 3.2.13 on 2022-12-26 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0023_auto_20220710_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='cerificate',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='expire',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='issuer',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
    ]
