# Generated by Django 3.2.13 on 2022-12-28 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0024_auto_20221226_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfo',
            name='cerificate2',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='cerificate3',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='expire2',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='expire3',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='issuer2',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bioinfo',
            name='issuer3',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
    ]
